### PR TITLE
Added color for fatal messages

### PR DESCRIPTION
**Pull request by WajahatAliAbid**
I was using this and realized fatal logs were sending good bar in slack messages. It's a small fix for that. Please push and deploy it to nuget :)

### CODE REVIEW

**Comment by alanedwardes** [comment]
Looks great! Mind bumping the patch version? https://github.com/Narochno/Narochno.Serilog.Slack/blob/master/src/Narochno.Serilog.Slack/LoggerConfigurationExtensions.cs#L5

It will push automatically when merged :)

**Comment by WajahatAliAbid** [comment]
@alanedwardes can you check if this fills the requirement for bumping the patch version? :)

**Review by alanedwardes — APPROVED** [review]

**Comment by alanedwardes** [comment]
Thanks!

**Comment by alanedwardes** [comment]
This version is now on NuGet.org! https://www.nuget.org/packages/Narochno.Serilog.Slack/3.0.1

**Comment by WajahatAliAbid** [comment]
Thanks :)

**Pull request merged**
